AWSTemplateFormatVersion: "2010-09-09"
Description: Launch an EC2 instance with a security group

Resources:

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: vpc-0ed54be816b294d12       # <-- Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316   # Amazon Linux 2 AMI (us-east-1)
      KeyName: project_key            # <-- Replace with your Key Pair name
      SubnetId: subnet-012390fac2a3b8314       # <-- Replace with your Public Subnet ID
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      Tags:
        - Key: Name
          Value: CF-EC2-Instance
